# Setup
title:               品客的洋芋片工廠
tagline:             '品客'
description:         '品客的部落格</a>.'
url:                 https://davislin.github.io
baseurl:             '/blog/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Davis Lin
  url:               https://davislin.github.io/blog/
  email:             smartdavislin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
